### ISSUE TITLE
Atom feed

### ISSUE THREAD

**Issue by ghost** [fchollet/keras-blog#3]
The Atom feed under the `<head>` tag on http://blog.keras.io/ points back to http://blog.keras.io/ instead of an actual Atom feed.

If you add `FEED = FEED_ATOM = 'feed.xml'` to your Pelican config, it should automatically generate the feed.

**Comment by uetchy** [comment]
This problem looks continuing. I can't fetch blog feed.

```
<link href="http://blog.keras.io/" type="application/atom+xml" rel="alternate" title="The Keras Blog ATOM Feed">
```

**Comment by kchodorow** [comment]
Still an issue.
